/**
 * GENERATED FILE — Keith Yackey's complete content library for RAG.
 *
 * Sources:
 *   - 100 Married Game Podcast episodes (RSS feed)
 *   - 107 Private Money Secrets episodes (relationship-relevant filtered)
 *   - 13+ guest podcast appearances (EOFire, Order of Man, Dad Edge, etc.)
 *   - 17 hand-written framework descriptions
 *
 * Total entries: 141 content chunks
 * Generated: 2026-03-23T19:26:58.578Z
 */

export interface ContentSeed {
  id: string;
  text: string;
  sourceType: 'FRAMEWORK' | 'PODCAST' | 'BOOK' | 'COACHING_SESSION';
  dial?: string;
  topic: string;
}

export const KEITH_CONTENT_SEEDS: ContentSeed[] = [
  {
    id: 'podcast:mg:f2ad2325-3007-4e2c-99f2-e060c6ca87ea',
    text: `In this week's episode, Jesse and Keith debut a brand new segment: Red Flag or Green Light. Listeners sent in real-life relationship scenarios—and it's up to your favorite couple to call it like they see it. Is it a major red flag or a green light to move forward? Nothing is off the table. From dating dilemmas to married mayhem, Jesse and Keith break it all down with their signature mix of honesty, humor, and heat. Tune in, see where you stand, and find out if your situation is headed for a stop sign or full speed ahead.`,
    sourceType: 'PODCAST',
    topic: 'Married Game Podcast: Red Flag, Green Light',
  },
  {
    id: 'podcast:mg:b53ea950-c9a2-4fe7-a59e-d8b0986e2e8d',
    text: `In this episode, we introduce our brand new segment "He Said, She Said"—where we break down real relationship dynamics from both sides of the bed. Plus, Jesse and Keith can't stop laughing about Keith's latest gym fashion statement: short shorts that are turning all the heads (including some he didn't expect). Tune in for laughs, real talk, and the truth every successful man needs to hear about marriage.`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Married Game Podcast: He Said, She Said',
  },
  {
    id: 'podcast:mg:9fb26f9c-9eaf-4891-a8d7-56b8a4a2981d',
    text: `Joining us today is Justin Wenzel, a transformative coach and dynamic entrepreneur based in Huntington Beach, California. As the founder and CEO of JWX Inc., Justin has dedicated his life to helping others overcome major personal challenges—including addiction, depression, anxiety, and obesity. Through a powerful blend of mindset, fitness, and nutrition coaching, he empowers his clients to unlock lasting transformation and achieve both personal and professional growth. Get ready for an inspiring conversation with someone who's walked the path and now guides others to do the same.`,
    sourceType: 'PODCAST',
    dial: 'PLAYER',
    topic: 'Married Game Podcast: Sobriety and Strength: Justin Wenzel',
  },
  {
    id: 'podcast:mg:81ad6fe2-8c53-4517-8eac-afe80fb95beb',
    text: `NEW SEGMENT ALERT! This week on the Married Game Podcast, Keith and Jesse unleash "Your Turn To Finish" — where they read half a sentence... then drop their OWN wild, honest, and hilarious endings. You never know what's coming next! Plus, Keith dives deep into the three biggest fears most men face when it comes to making real friendships.`,
    sourceType: 'PODCAST',
    topic: 'Married Game Podcast: Your Turn To Finish',
  },
  {
    id: 'podcast:mg:c1e8c4bf-1dd5-45f8-9a7b-c020bcbf149f',
    text: `In this episode, Keith sits down with Army Ranger veteran and former Seattle police officer Greg Anderson. Greg made headlines when he took a stand for what he believed in during the COVID era, a decision that ultimately cost him his job but defined his integrity. They dive deep into the warrior mindset, the experience of accepting death in combat, and how that profound shift can change a man forever.`,
    sourceType: 'PODCAST',
    dial: 'POWER',
    topic: 'Married Game Podcast: Warrior Wisdom with Greg Anderson',
  },
  {
    id: 'podcast:mg:b59d1cc0-75c0-46a1-add0-48a59acc9a48',
    text: `​In this episode, Keith and Jesse dive into the world of penny-pinching partners, exploring how differing views on spending can stir up some marital mischief. They share hilarious anecdotes and practical tips on keeping the love alive when wallets clash. Plus, don't miss the debut of their new segment, "The Confession Tapes," where they unravel juicy confessions and dish out advice with their signature flair. Tune in for a rollercoaster of laughs, insights, and a sprinkle of drama!​`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Married Game Podcast: Confession Chair Chronicles: Secrets, Scandals, and Cheapskates!',
  },
  {
    id: 'podcast:mg:e4af2fb4-48b9-4ba8-adf4-840fdd60bf6b:0',
    text: `In this week's episode, Keith and Jesse introduce an exciting new segment called Mythbusters, where they break down popular marriage myths and explain why they're not always as they seem. From common misconceptions to surprising truths, they dive into all the things we think we know about relationships and set the record straight. Things take a curious turn when Jesse reveals why she told Keith she needed to brush her teeth before a certain intimate moment. What's the story behind this request?`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Married Game Podcast: First, I need to brush my teeth',
  },
  {
    id: 'podcast:mg:e4af2fb4-48b9-4ba8-adf4-840fdd60bf6b:1',
    text: `Tune in for a fun and eye-opening discussion filled with laughs, personal stories, and a whole lot of truth!`,
    sourceType: 'PODCAST',
    dial: 'PLAYER',
    topic: 'Married Game Podcast: First, I need to brush my teeth',
  },
  {
    id: 'podcast:mg:4827202e-4524-4d54-a6b7-d9aa04f6ac56',
    text: `In this week's episode, Keith and Jesse introduce a brand-new segment: Love It or Leave It! They'll dive into a series of situations, debating which ones they'll love and which ones they'll leave behind. Will they embrace it or walk away? Tune in to find out and enjoy the laughs, surprises, and heated takes along the way.`,
    sourceType: 'PODCAST',
    topic: 'Married Game Podcast: Love It, or Leave It',
  },
  {
    id: 'podcast:mg:066eb7a2-bd25-4324-b753-26b43e3474fd',
    text: `In this episode, Keith and Jesse dive into how poor planning during their time in Mexico led to some unexpected self-reflection. They share their personal experiences and the lessons they learned from this adventure. Plus, we're introducing a brand-new segment, The Statistics of Happily Ever After, where we explore the numbers behind what makes relationships and life truly fulfilling. Tune in for some insightful discussions and a little bit of humor along the way!`,
    sourceType: 'PODCAST',
    dial: 'PLAYER',
    topic: 'Married Game Podcast: No Plan, Just Mexico Madness',
  },
  {
    id: 'podcast:mg:9aed478d-7ac3-4243-a643-9c62844de069',
    text: `On today's episode, we dive into the reality that being happy all the time just isn't possible. Keith opens up about how he navigates his moods, especially after his recent testosterone shot, and how he leans on Jesse for support during those tougher moments. We also explore how to create the perfect date night for your wife—tips that will make her feel special and appreciated. Plus, we've got some fun surprise segments at the end that you won't want to miss!`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Married Game Podcast: Sixty Eight & I\'ll Owe You One',
  },
  {
    id: 'podcast:mg:bd4de203-04be-4aca-a009-04bfd284d32c',
    text: `In this episode, we dive into the big question: Does my relationship advice actually work on my wife? Join us as we answer some of the most interesting questions asked by our listeners and get real about what truly works (and what doesn't!). Plus, don't miss our fun new segment – Fill in the Blank! It's a mix of laughs, insights, and some unexpected moments. Tune in now and let us know your thoughts!`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Married Game Podcast: Does My Relationship Advice Actually Work on My Wife?',
  },
  {
    id: 'podcast:mg:9d1b4f0c-5c44-4a19-bae6-9161bf9cfaf5',
    text: `This Week on The Married Game: Staying Connected, Even from Miles Apart! In this episode, Keith and Jess dive into the challenges and strategies of maintaining a strong connection while Keith is on the road. Whether it's communication, trust, or intimacy, they share their tips for staying close despite the distance. Don't miss this honest and insightful conversation on how to keep the spark alive when life pulls you in different directions. Tune in now for actionable advice on making long-distance moments work for your marriage!`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Married Game Podcast: Miles Apart, Still Connected- Keeping the Spark Alive While Traveling',
  },
  {
    id: 'podcast:mg:362e1517-8458-43a3-b364-c7d18f97ca28:0',
    text: `In today's episode, we're excited to celebrate the release of The Married Game with a special podcast! Keith and Jess dive into the key features of the book, sharing their insights and highlighting what makes it exceptional. As they reflect on the content, they also brainstorm ideas for potential future installments. Additionally, they discuss their weekend experiences surrounding their love for each other, giving listeners a behind-the-scenes idea of what a great Valentine's day consists of.`,
    sourceType: 'PODCAST',
    topic: 'Married Game Podcast: The Married Game Book Is Here',
  },
  {
    id: 'podcast:mg:362e1517-8458-43a3-b364-c7d18f97ca28:1',
    text: `To wrap things up, they answer questions from you, the listeners, providing thoughtful responses and engaging with your thoughts and feedback on the topics covered. Don't miss this fun and insightful episode!`,
    sourceType: 'PODCAST',
    dial: 'PLAYER',
    topic: 'Married Game Podcast: The Married Game Book Is Here',
  },
  {
    id: 'podcast:mg:f36ad11f-dbea-4d2c-966f-9eefa51a634e',
    text: `As a follow-up to last week's episode, we take a deep dive into common scenarios involving the stereotype of a "nagging wife," but this time from a man's perspective. We discuss how to navigate or respond to such situations. Keith and Jess share their personal insights on the topic and break down their thought processes. Let's listen in!`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Married Game Podcast: The Man\'s Solution To A Nagging Wife',
  },
  {
    id: 'podcast:mg:59e6e6e1-44d6-4a85-96d4-fa5a8c5f7154',
    text: `In today's episode, the word of the day is "nagging." Keith and Jesse explore why a man may not even realize why he's on the receiving end of this behavior from his loved one. They also provide a list of common examples of "nagging," discuss the reasons behind this behavior, and uncover the deeper meaning driving such remarks. Let's listen in!`,
    sourceType: 'PODCAST',
    dial: 'POWER',
    topic: 'Married Game Podcast: The Key to fix a woman\'s nagging',
  },
  {
    id: 'podcast:mg:cace0a41-e1fe-4c6c-a5ff-e22b29254371',
    text: `In today's episode of the Married Game Podcast, hosts Keith and Jesse dive into the topic of manipulation, exploring how it affects relationships and why men may struggle with the idea that their wives don't desire sex as much as they do. Keith and Jesse provide a new perspective, suggesting that true connection comes from genuine attraction, not manipulation, and that men should focus on being the best version of themselves to create a lasting bond. Let's listen in!`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Married Game Podcast: I Created All Our Problems: Confessions of a Recovering Manipulator',
  },
  {
    id: 'podcast:mg:918eb228-82b7-4136-9874-ffaf543ef8bc',
    text: `In today's episode, Garrett Gunderson joins us to share valuable insights on overcoming scarcity and navigating with a different mindset. He explores the connection between money and relationships, emphasizing the importance of adopting the right approach to finances. Shifting your mindset is crucial to making this transformation. What most men prioritize is getting paid and getting laid. In today's episode, audiences gain valuable perspectives on both. Let's listen in! Connect with Garrett Gunderson at Instagram: @garrettbgunderson garrettgunderson.com`,
    sourceType: 'PODCAST',
    dial: 'PRODUCER',
    topic: 'Married Game Podcast: Creating Financial Freedom',
  },
  {
    id: 'podcast:mg:687cca27-6088-4696-b759-23f4408acbc6',
    text: `In the first episode of 2025, Keith and Jesse tackle the issue of how society has conditioned men to feel entitled to sex. They discuss the problematic expectations placed on men regarding sex and relationships. The conversation highlights the importance of effort and mutual respect in building meaningful connections. They emphasize that a genuine bond is essential for any intimate relationship to develop. The episode encourages listeners to challenge societal norms and prioritize connection over entitlement.`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Married Game Podcast: False Entitlement',
  },
  {
    id: 'podcast:mg:ec3a03a0-20e9-48b9-b842-a49fcc22a47a',
    text: `In this special episode, Keith focuses on the concept of 'giving her energy' and 'taking her energy,' breaking down what it means for someone who may be struggling. He emphasizes the importance of becoming the interviewer rather than the interviewee in these moments. Plus, Keith shares his personal cell phone number, offering support to those who need help immediately. If you need to reach out, text him at (949) 414-4302`,
    sourceType: 'PODCAST',
    topic: 'Married Game Podcast: Quit Making Your Wife The Boss',
  },
  {
    id: 'podcast:mg:e60ead25-d5db-49c5-b03b-c0d4bff572cb',
    text: `On today's episode, Keith and Jess dive into what it truly means to connect with and understand women. They discuss the art of speaking to a woman's soul—building a connection that encourages openness and deeper conversations. It's all about stepping into her world and forging genuine bonds. Let's listen!`,
    sourceType: 'PODCAST',
    topic: 'Married Game Podcast: Speaking the Language of Women',
  },
  {
    id: 'podcast:mg:3d153951-c1bc-4ac8-9060-8fe66e03837d',
    text: `In today's episode, Keith and Jess dive into the importance of creating inside jokes in relationships. They explore how sharing a unique humor or reference—something only the two of you understand—builds trust and strengthens the bond on a deeper level. Don't miss this fun and insightful conversation Let's listen in!`,
    sourceType: 'PODCAST',
    dial: 'PLAYER',
    topic: 'Married Game Podcast: Inside Jokes',
  },
  {
    id: 'podcast:mg:121ce355-9b94-4814-ba00-dcc2dc80646f:0',
    text: `In this episode, Keith and Jess delve into strategies for sidestepping unnecessary emotional stress, mental strain, and unproductive situations. By emphasizing the importance of proactive planning and open communication, they underscore how preparation can prevent minor challenges from escalating into significant problems. They discuss how addressing potential concerns early and fostering honest conversations can create a smoother path forward, reducing misunderstandings and promoting harmony in both personal and professional settings.`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Married Game Podcast: Love and Logistics',
  },
  {
    id: 'podcast:mg:121ce355-9b94-4814-ba00-dcc2dc80646f:1',
    text: `Through their insights, listeners gain practical advice to navigate life's inevitable hurdles with greater ease and confidence.`,
    sourceType: 'PODCAST',
    topic: 'Married Game Podcast: Love and Logistics',
  },
  {
    id: 'podcast:mg:601052ce-af14-4d06-a206-1586ca8076d7',
    text: `In today's episode, Jesse Joy is back and we continue were we left off on our previous podcast involving a card game for conversation starters. We hear her reception of the card game as well as further diving deep into the importance of reintroducing conversations between couples. Let's listen in!`,
    sourceType: 'PODCAST',
    topic: 'Married Game Podcast: Get Laid With Card Games',
  },
  {
    id: 'podcast:mg:914c0e68-d47a-4400-b816-33f5cc0e81fb',
    text: `In todays episode, Keith talks about the struggle every successful man relates to when it comes to figuring it out on your own. The feeling of disempowerment when you are unable to have all the answers when it comes to issues with your relationship. Keith wants to let you know, its ok to ask for help as he can relate to your issues. Let's listen!`,
    sourceType: 'PODCAST',
    topic: 'Married Game Podcast: Having All The Answers',
  },
  {
    id: 'podcast:mg:2cf99363-3690-400a-82cc-8b50d42fa396',
    text: `In this episode, Keith delves into the secret to maintaining long-term attraction through meaningful emotional conversations. Using a card game, he makes it enjoyable and simple to initiate new discussions that foster deeper connections with your loved one. Let's listen in!`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Married Game Podcast: Past the Surface Level Conversations',
  },
  {
    id: 'podcast:mg:1733fc5d-bfc1-450e-b8d2-8e4922c7aa0b',
    text: `We have another set of questions for today's podcast, where we continue to explore the inquiries that help us better understand one another. This time, Keith and Jesse share personal stories to convey their points, while also incorporating their expertise on the topic. Let's listen in!`,
    sourceType: 'PODCAST',
    topic: 'Married Game Podcast: Insights Into Marriage',
  },
  {
    id: 'podcast:mg:a47a23a6-b700-4036-9cd8-ddd59a3528f6',
    text: `In today's episode, Keith and Jess dive deep into your questions, providing thoughtful and detailed responses. Each of them offers unique insights, showcasing their individual perspectives and expertise. Even when they disagree, they present compelling arguments, enriching the discussion with diverse viewpoints. Their engaging exchange not only answers your inquiries but also sparks further reflection and dialogue among listeners. Whether you're looking for expert advice or simply enjoy a good debate, Keith and Jess ensure a captivating and informative experience. Let's listen in!`,
    sourceType: 'PODCAST',
    topic: 'Married Game Podcast: Questions To Reveal Truths',
  },
  {
    id: 'podcast:mg:875c1d7a-7d24-479f-a364-a10c31c0e323',
    text: `In this episode, join Keith and Jesse as they discuss the key elements of keeping a successful relationship thriving. From openly addressing needs, desires, and truths, to cultivating intimacy, they share personal stories aimed at inspiring positive transformation within your own relationship. Let's listen in!`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Married Game Podcast: Keeping the Hope Alive',
  },
  {
    id: 'podcast:mg:81feae11-a03a-43c9-a34b-a2647d3eb45d:0',
    text: `In today's episode, we delve into the profound journey of Keith and Jesse as they undergo significant personal and collaborative growth, propelling them toward a new level of development. The central focus of the podcast revolves around Keith's profound perspective on the necessity of pushing beyond comfort zones in a relentless pursuit of excellence. As they share their experiences, they emphasize the relentless pursuit of progress as an ongoing and essential endeavor for all individuals.`,
    sourceType: 'PODCAST',
    topic: 'Married Game Podcast: A new potential with growth',
  },
  {
    id: 'podcast:mg:81feae11-a03a-43c9-a34b-a2647d3eb45d:1',
    text: `Join us as we explore the ever-present theme of growth and its profound impact on personal and professional transformation. Let's listen in!`,
    sourceType: 'PODCAST',
    topic: 'Married Game Podcast: A new potential with growth',
  },
  {
    id: 'podcast:mg:e2d73f59-962b-4f08-b10e-dfc77f8cce79',
    text: `In today's special podcast, Keith and Jesse are coming back from a session at the open mat Jiu Jitsu. Analogies between life and Jiu Jitsu are discussed and how someone can excell, even during moments of failure so that they may learn from it. Listen in to how the session went and how they became better due to it. Lets listen in!`,
    sourceType: 'PODCAST',
    topic: 'Married Game Podcast: Life and Jiu Jitsu',
  },
  {
    id: 'podcast:mg:48c74a3b-d260-42d0-aa35-1012ccdf3bfa',
    text: `In today's episode, Keith and Jess discuss a husbands role in dad mode, sharing parental priorities, and performing tasks without the intention of being loved. Learning how to show up to display true love is a big theme in this podcast. Let's listen in!`,
    sourceType: 'PODCAST',
    dial: 'PARENT',
    topic: 'Married Game Podcast: Just because she\'s wrong doesn\'t mean I\'m right',
  },
  {
    id: 'podcast:mg:8e389b04-85bb-40b0-a4a3-fab91804b251',
    text: `In today's episode, Keith and Coach Carter talk about what it takes to be as efficient and successful with your body, which in turn, takes an effect on your life overall. Being accountable, staying on the path to success, and how to do it is in this conversation. Let's listen in! Follow Coach Carter at instagram.com/cartermontgomery_ and theascensionfitness.fit/home`,
    sourceType: 'PODCAST',
    dial: 'PLAYER',
    topic: 'Married Game Podcast: Taking Things To The Next Level',
  },
  {
    id: 'podcast:mg:4dcf8d89-8ac7-4f2b-80d0-7f0950540bd5',
    text: `In today's episode, the overarching theme to the episode is Quality of Life. Keith talks about the healing process, what it means to understand someone else who has similar experiences as you do, and why we are all miracles. Let's listen in!`,
    sourceType: 'PODCAST',
    topic: 'Married Game Podcast: Quality of Life',
  },
  {
    id: 'podcast:mg:76228310-80d6-4c89-aab8-20d1c2306c79',
    text: `In today's special episode, a special guest stops by the mancave and who else, but Spectacular Smith himself. Together, Spectacular, Keith, and Jesse discuss business and relationships. The knowledge and how they acquired it through experience and wanting to improve as an individual is shown here. You do not want to miss out on this raw and detailed conversation. Lets listen in! Check out Spectacular at: Socialmediamasterclass.com Twitter/X Instagram @iamspectacular on social media`,
    sourceType: 'PODCAST',
    dial: 'PRODUCER',
    topic: 'Married Game Podcast: Spectacular Words of Wisdom',
  },
  {
    id: 'podcast:mg:25e9fa17-abc7-416b-b6bd-8312e8359bd2',
    text: `In todays episode, Keith and Jesse discuss the frame involving abundance and scarcity. Not just from an financial perspective, but a relationship respective as well. Keith and Jess break down what it means to not settle for anything less when you are able to abandon scarcity and believe in abundance. Let's listen in!`,
    sourceType: 'PODCAST',
    dial: 'PRODUCER',
    topic: 'Married Game Podcast: Abundance and Scarcity',
  },
  {
    id: 'podcast:mg:7d49f3e3-f00f-432f-b33f-1cc615cd8d3c',
    text: `In today's episode, Keith praises Jesse Joy for steeping up over the weekend during the Ascend Brotherhood. Stories involving understanding growth, emotions, and a dishwasher stand out during the episode. Let's listen!`,
    sourceType: 'PODCAST',
    topic: 'Married Game Podcast: When Your Partner Steps Up',
  },
  {
    id: 'podcast:mg:85ec9d5c-0518-4b81-80a9-824be8b01150',
    text: `In today's episode, Keith and Jesse explain how reframing needs, wants, and the reality from a partnership. Conversations about becoming "the guy" and becoming more attractive are central points in the podcast as well as creating a world to be desired by others is a central point in the examples and stories told by both Keith and Jesse. Let's listen in!`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Married Game Podcast: Escaping the Mom Matrix',
  },
  {
    id: 'podcast:mg:77b53068-40d5-4e06-9c75-dc00e3cbc1d8',
    text: `In this special mid-week episode, We have Mark Moss as a special guest talking to Keith about various topics. Stories and tips involving connecting with the kids, how a family that plays together, stays together, keeping a marriage alive and well, and navigating through money are all told here. Let's listen in!`,
    sourceType: 'PODCAST',
    dial: 'PARENT',
    topic: 'Married Game Podcast: Life, Marriage, and the Game of Money',
  },
  {
    id: 'podcast:mg:759cca59-642d-4007-add5-cda77164d307',
    text: `In this episode, Keith and Jess discuss the needs and wants someone will desire in a relationship. Keith provides in detail the necessity to be unapologetic for your needs in order for an individual to be truly free. Let's listen in!`,
    sourceType: 'PODCAST',
    topic: 'Married Game Podcast: What You Really Want',
  },
  {
    id: 'podcast:mg:bbb3d496-841e-4670-97e4-2300a6d20283',
    text: `In Today's episode, Keith and Jess answer the questions you, the audience, have asked. Questions regarding your significant other that seem complicated or hard to approach/answer but are broken down into digestible answers by Keith and Jess. Let's listen in!`,
    sourceType: 'PODCAST',
    topic: 'Married Game Podcast: Understanding The Game',
  },
  {
    id: 'podcast:mg:c6c2c24f-2ddf-4865-a6c5-650480c4f72e',
    text: `In today's episode, Keith and Jess discuss the importance of the partner dial. Potentially the most important dial of them all, they discuss how the partner dial has improved their relationship and how it could help others as well who are lacking a connection or friendship within the relationship. Let's listen!`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Married Game Podcast: The Partner Dial within your Marriage',
  },
  {
    id: 'podcast:mg:2aacf510-6624-495b-a5bd-7fec85456086',
    text: `In today's episode, Keith has a tough but much needed conversation about what is acceptable in a relationship. What needs to be accomplished from both sides in order to stand firm on what to expect and accept in a relationship. Let's listen!`,
    sourceType: 'PODCAST',
    topic: 'Married Game Podcast: What to Accept In Your Relationship',
  },
  {
    id: 'podcast:mg:0867e084-ec04-4e01-8abe-81a9d851910d',
    text: `Today Keith and guest Dennise Crosby discuss everything marriage related including foundations, approach to issues, and solutions or ways to go about it. The best part is, that they both have unique applications to helping men save their marriage or strengthen their relationship. Follow Authentic Man on YouTube @AuthenticMan Lets listen in!`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Married Game Podcast: Similar Yet Unique Approach',
  },
  {
    id: 'podcast:mg:906e08cc-2397-415e-911d-39fa2f0b1a2f',
    text: `In this episode, Keith and Jesse talk about the need to constantly evaluate oneself to see how close (or far) someone is from achieving their needs in marriage. Questions from listeners are asked and are answered from 2 different perspectives. Lets listen in!`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Married Game Podcast: Layers of Life',
  },
  {
    id: 'podcast:mg:337f130b-0ca4-4d46-824e-2f14435e675d',
    text: `In this episode, Keith and Jess discuss how to keep the dating aspect in your relationship well into your marriage. From the beginning of a relationship to your current state, they provide ideas on how to keep it fun and fresh every time. Let's listen in!`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Married Game Podcast: The Good Dating Life',
  },
  {
    id: 'podcast:mg:bb5e6734-880d-4208-87d3-7f263f27811b',
    text: `In today's episode, Keith and Jesse discuss how talking with one another (or with a therapist) has helped change each other's mindset and allowed for both to move forward with a positive outcome for both partners. This conversation aims to give perspectives while also providing a learning moment to become better. Let's listen in!`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Married Game Podcast: Sharing Reveals All',
  },
  {
    id: 'podcast:mg:03db9725-26b6-4d38-af3a-59cf2cad890a',
    text: `In this episode, Keith and Jesse talk about how sharing will bring out the best version of each other. Telling each other what you truly want to say will triumph over what could happen such as hurting your partner's feelings. This takes courage and Keith gives examples on how to overcome this fear. Let's listen in!`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Married Game Podcast: Continue To Learn From Each Other',
  },
  {
    id: 'podcast:mg:2a4126d4-4085-47af-8028-20ab5416e0be',
    text: `In this episode, Keith Yackey and Jesse talk about an important subject: Words Matter. They dive deep into the implications and possible results due to a message or statement being misunderstood because of misplaced words. Let's listen in!`,
    sourceType: 'PODCAST',
    dial: 'POWER',
    topic: 'Married Game Podcast: The Importance of Words',
  },
  {
    id: 'podcast:mg:0c425693-ebd2-4f6f-bcaa-c2863b903668',
    text: `In this episode, Keith talks about expectations and the potential downfalls associated with such assumptions and what someone can do to avoid this. Topics such as communication and ego are mentioned alongside personal stories told by Keith and Jess. Lets listen in!`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Married Game Podcast: Managing Marital Expectations',
  },
  {
    id: 'podcast:mg:98af9f89-db18-4548-a04a-97a5032bcaf0',
    text: `In todays episode, Keith dives into the attractions of both genders and how to be attractive to the other. We will listen to a simplified but effective method on how to showcase attractive traits to your significant other. Keith discusses what men look for while Jess lists what a lady wants from her other half. Both sides are discussed in this episode. Listen in!`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Married Game Podcast: What Is Actually Attractive To A Male And A Female',
  },
  {
    id: 'podcast:mg:e143b727-fa08-4f5c-80fd-6699aeb23869',
    text: `In this episode, Keith explains the power of plant medicine and how it has changed his life. A brand new experience has allowed Keith to reframe his view on life and redefine his actions moving forward. The change Keith Yackey has encountered is laid all out in this episode. Listen in!`,
    sourceType: 'PODCAST',
    dial: 'POWER',
    topic: 'Married Game Podcast: The Journey with Plant Medicine',
  },
  {
    id: 'podcast:mg:2555c90d-3ae9-4431-9dcf-213b2194ce9c',
    text: `In this episode, Keith and MMA fighter Adam Lynn dive into their beginnings for joining jiu-jitsu and why every man should participate in a self defence martial art or combat sport. From recognizing your vulnerabilities to discovering your full potential, they discuss fighter instincts, the realization to want to improve oneself, and what it takes to get there. Listen in! ____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    topic: 'Married Game Podcast: Improve Your Fighting Skills And Your Life',
  },
  {
    id: 'podcast:mg:65e9282b-c4f6-495b-92f5-ca4378137bce',
    text: `In this episode, Keith and Jesse dive into one of the biggest challenges every couple faces: handling fights and finding ways to reconnect. They discuss shortening conflict durations and reducing the time needed to make up. Drawing from personal experiences and insights from the Gottman Institute, they explore strategies for effective bids for reconnection and the importance of understanding and receiving these bids. Listen in! ____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    topic: 'Married Game Podcast: From Fights To Forgiveness',
  },
  {
    id: 'podcast:mg:01e2012b-7fbd-4d9b-822a-962eaf2af7d2',
    text: `In this episode, Keith and Jesse dive into a lively Q&A, tackling a listener's dilemma about feeling belittled by his wife's schoolmarm tone. They explore the triggers, misunderstandings, and effective communication strategies to transform nagging into nurturing. With humor and personal anecdotes, they reveal the secrets to maintaining empathy and understanding in marriage, even during stressful times. Listen in! ____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Married Game Podcast: When Schoolmarm Meets Dad Mode',
  },
  {
    id: 'podcast:mg:88e73cc3-3e10-4347-ab69-0d2b66bf415d',
    text: `In this episode, Keith is joined by Alan Belcher and they delve into the mindset of champions, exploring discipline, resilience, and identity through Alan's journey from a downward spiral to reinvention. They discuss overcoming ego, embracing growth, and the transformative power of martial arts in shaping character and ambition. Listen in! ____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    dial: 'PRODUCER',
    topic: 'Married Game Podcast: Unleashing The Champion Within',
  },
  {
    id: 'podcast:mg:8374b12e-c2e1-4b8c-a54c-89ed3fd83eee',
    text: `In this episode, Keith and Jesse delve into the transformative power of freedom in relationships, particularly in marriage. They discuss the necessity of genuine self-belief when offering advice to others, emphasizing the importance of authenticity and honesty. They advocate for open communication and mutual respect in relationships and highlight the significance of self-awareness, personal growth, and the role of ego in hindering or facilitating true freedom. Listen in! ____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Married Game Podcast: Relationship Freedom',
  },
  {
    id: 'podcast:mg:20760633-8546-4d65-9984-3fff20151b4b:0',
    text: `In this episode, Keith and Jesse delve into the pervasive issues of guilt and shame in people's lives, examining the contrast between traditional religious perspectives and the teachings of Jesus. As they explore Jesus's messages of joy, love, and peace, they challenge conventional religious views, dissecting topics like masturbation, relationship dynamics, and the pitfalls of manipulative religious leaders. This conversation aims to unravel societal conditioning, promote self-discovery, and inspire a shift towards a life filled with authentic joy and love. Listen in!`,
    sourceType: 'PODCAST',
    topic: 'Married Game Podcast: Joy, Peace, Love And Jesus',
  },
  {
    id: 'podcast:mg:20760633-8546-4d65-9984-3fff20151b4b:1',
    text: `____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    topic: 'Married Game Podcast: Joy, Peace, Love And Jesus',
  },
  {
    id: 'podcast:mg:9996bd77-cdc8-4161-90c1-e822b6b835bd:0',
    text: `In this episode, Keith and Jesse embark on a riveting journey through Keith's transformative years, from a devout pastor to a man driven to understand the intricacies of attraction. With candid humor, they explore his pursuit of centerfold conquests, unveiling insecurities, rejection, and the psychological evolution that ultimately led to a profound understanding of relationships and desire. This episode delves into the raw, unfiltered path of self-discovery and growth in the realm of love and intimacy. Listen in!`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Married Game Podcast: From Pastor To Player',
  },
  {
    id: 'podcast:mg:9996bd77-cdc8-4161-90c1-e822b6b835bd:1',
    text: `____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    topic: 'Married Game Podcast: From Pastor To Player',
  },
  {
    id: 'podcast:mg:b1dca758-e8ac-4a4f-bb5a-0e633fed1005',
    text: `In this episode, Keith and Jesse dive into the controversial debate of whether men truly desire a "savage queen" or a supportive wife. They challenge societal norms, share personal experiences, and advocate for independent thinking. The episode explores the dynamics of relationships, questioning conventional beliefs and emphasizing the importance of individuality and genuine connection. Listen in! ____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Married Game Podcast: The Myth Of The Savage Queen',
  },
  {
    id: 'podcast:mg:ff24d776-abdf-436c-9f7d-fb5f042ed637:0',
    text: `In this episode, Keith and Jesse discuss Jessie's captivating life story, from growing up with a rocker dad to finding her path in life. They talk about her wild childhood memories, her deep insights into relationships, her fun-loving spirit, unwavering loyalty, and innate ability to bring joy to everyone around her. From her adventurous dating life to her transformative journey of self-discovery, Jessie shares candidly, touching on moments of vulnerability and strength.`,
    sourceType: 'PODCAST',
    dial: 'PARENT',
    topic: 'Married Game Podcast: The Real Jesse Joy',
  },
  {
    id: 'podcast:mg:ff24d776-abdf-436c-9f7d-fb5f042ed637:1',
    text: `Keith and Jessie also invite you to explore the complexities of love, resilience, and the beauty of embracing your true self. Listen in! ____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    topic: 'Married Game Podcast: The Real Jesse Joy',
  },
  {
    id: 'podcast:mg:5fb532ea-5a95-48a8-b4ef-cd211da2e30e',
    text: `In this episode, Keith and Jesse dive into the intricacies of the "parent dial" as they candidly discuss the trials and joys of parenting. From the early struggles to the evolving dynamics, they explore the impact on relationships, the unique challenges faced, and the transformation that comes with time and understanding. Listen in! ____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    dial: 'PARENT',
    topic: 'Married Game Podcast: Be The Person That Invests In Your Children',
  },
  {
    id: 'podcast:mg:6fd5ba39-5982-4e32-bbbb-4e9ef39783c1:0',
    text: `In this episode, Keith and Jesse delve into the transformative power of embracing a day-one mentality in marriage. They share personal stories, revealing the importance of showing up as a partner, producer, parent, player, and in your power. As they discuss the intricacies of their own relationship, they unveil a groundbreaking perspective on married game that defies conventional wisdom, offering game-changing insights for both married and single individuals seeking lasting connection and fulfillment. Listen in!`,
    sourceType: 'PODCAST',
    dial: 'PARENT',
    topic: 'Married Game Podcast: The Sex Life You\'ve Always Dreamed Of',
  },
  {
    id: 'podcast:mg:6fd5ba39-5982-4e32-bbbb-4e9ef39783c1:1',
    text: `____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    topic: 'Married Game Podcast: The Sex Life You\'ve Always Dreamed Of',
  },
  {
    id: 'podcast:mg:30fad8e1-381a-4f20-83f8-fc1943a9e415',
    text: `In this episode, Keith and Jesse share personal insights on the importance of having 'game' within a marriage. Unveiling the deceptive partner dial, they candidly discuss their own struggles and growth, exploring how understanding and enthusiastic support for each other's passions can reignite the spark in your relationship. Listen in! ____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Married Game Podcast: Unmasking The Real Game In Relationships',
  },
  {
    id: 'podcast:mg:eef054b3-625e-4936-b06d-53eaab40d622',
    text: `In this episode, Keith is joined by Ed Baxter, and they discuss Ed's powerful journey from heartbreak to empowerment. Ed shares how he overcame the pain of being cheated on, discovered his authentic self, and transformed into a true badass. Learn the key insights, challenges, and triumphs as Ed guides men through the genuine attraction process, offering hope and light for those navigating their own path of healing and self-discovery. Listen in! ____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Married Game Podcast: From Betrayed To Badass With Ed Baxter',
  },
  {
    id: 'podcast:mg:ae66f7f3-50d6-47c5-a345-297ff867a4df',
    text: `In this episode, Keith and Jesse are joined by Taylor Carr, aka tayfemme, femininity and dating coach, and they discuss Taylor's journey from overcoming health challenges to unraveling the complexities of modern relationships. They dive into the dynamics of feminine and masculine energies, the pitfalls of routine, and the key to keeping the flame alive in long-term love. Listen in! ____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    dial: 'PLAYER',
    topic: 'Married Game Podcast: The Feminine And Masculine Dance With Taylor Carr',
  },
  {
    id: 'podcast:mg:24f2dbfa-15b9-41af-9602-9bbf38ee8040',
    text: `In this episode, Keith is joined by Marni Kinrys, and they discuss the world of flirting, sharing personal anecdotes and expert insights. From decoding subtle cues to mastering the art of banter, they explore the keys to adding excitement and connection to relationships. Whether you're single or married, discover the playful strategies that elevate your dating and intimacy game. Listen in! ____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Married Game Podcast: Mastering the Art of Flirting With Marni Kinrys',
  },
  {
    id: 'podcast:mg:6944fa80-122a-4e9e-a6e0-0bce71e0e37d',
    text: `In this episode, Keith and Jesse toast to the holidays, diving into their date night, studio design, and reflecting on live event insights. They unpack women's initiation conditioning, roles, and societal pressures. They humorously dissect slug and overhyped personas at gatherings, sharing a powerful mindset shift for embracing family occasions with curiosity and authenticity, outlining what resonates most for a joyful holiday season. Listen in! ____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    dial: 'POWER',
    topic: 'Married Game Podcast: Holiday Traditions And Fake People',
  },
  {
    id: 'podcast:mg:93c6fd72-5ad4-4fe0-b65a-35f6fcf2a68d',
    text: `In this episode, Keith is joined by Jonathan Hika, and they discuss Jonathan's marital challenges, radical transformation, his courage to confront blindness, rebuild identity, and embrace change. His embrace of vulnerability, guided by Keith's coaching, unveils a newfound self-worth beyond physical transformation, showcasing a depth of resilience and self-discovery. Listen in! ____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    topic: 'Married Game Podcast: Personal Revolution With Jonathan Hika',
  },
  {
    id: 'podcast:mg:4db4a849-29ca-416e-8898-4c973d85e1ed',
    text: `In this episode, Keith and Jesse are joined by Brian and Tasha, who share their remarkable journey from a marriage teetering on the edge to a place of love, joy, and authenticity. Discover how Brian's transformation and Tasha's unwavering commitment led to a renewed connection and a thriving relationship. Their candid and inspiring story show how they rediscovered love, rebuilt trust, and reignited their relationship for the better. Listen in! ____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Married Game Podcast: Rebuilding Love With Brian and Tasha',
  },
  {
    id: 'podcast:mg:70074808-653a-4d35-823d-106451afdec8',
    text: `In this episode, Keith is joined by Larry Hagner, founder of The Dad Edge, and they discuss the world of fatherhood and explore the transformative power of becoming a better dad. They talk about the common struggles men face in their roles as fathers, the importance of communication, and the profound impact of simple changes in behavior. Discover how embracing the "dad edge" can lead to more fulfilling and connected relationships with your family. Listen in! ____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    dial: 'PARENT',
    topic: 'Married Game Podcast: Unlocking The Dad Edge With Larry Hagner',
  },
  {
    id: 'podcast:mg:99a7be47-d5cc-447b-9f1b-71da5d324c0f',
    text: `In this episode, Keith and Jesse explore the power of confronting fear, breaking free from conditioning, and embracing grace in both personal and relational growth. Discover how to unlock your full potential, challenge societal norms, and create the life you truly desire. Plus, they answer a listener's question on how to give and receive grace in challenging situations. Listen in! ____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    dial: 'POWER',
    topic: 'Married Game Podcast: Fear, Responsibility And The Power Dial',
  },
  {
    id: 'podcast:mg:6272f2d5-9ca7-48ca-9150-98c7172a4b06',
    text: `In this episode, Keith and Jesse explore the concept of "watering your partner" to create a thriving and passionate relationship. They share personal experiences, insights, and practical tips for daily relationship maintenance. Learn how consistent care and attention can lead to a stronger, more fulfilling connection, and discover why becoming a relationship "stud" is essential for both men and women. Listen in! ____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Married Game Podcast: Watering Your Partner',
  },
  {
    id: 'podcast:mg:7f408d25-a08d-4880-900a-942f1ebcbae7',
    text: `In this episode, Keith and Jesse dive deep into their transformative journey through the 75 Hard mental toughness program. They discuss the incredible benefits, the power of keeping your word to yourself, and the profound impact it has had on their lives and relationships. Discover how embracing discipline can lead to personal growth and create a path to true success and fulfillment. Listen in! ____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    dial: 'POWER',
    topic: 'Married Game Podcast: Challenging Your Mental Toughness',
  },
  {
    id: 'podcast:mg:5303c757-9b72-4657-a2d2-ce2bfccd62ba',
    text: `In this episode, Keith and Jesse discuss their rollercoaster love story, from a chance encounter at Hooters to a rocky breakup and eventual reconciliation. Discover the raw emotions, insecurities, and hard work that led to a resilient love built on trust, growth, and unwavering commitment. Their journey is a testament to the power of transformation and the enduring potential of love. Listen in! ____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    dial: 'PRODUCER',
    topic: 'Married Game Podcast: From A One-Night Stand To Lifelong Love',
  },
  {
    id: 'podcast:mg:5e088397-767d-42e0-ac72-e459b1cff7d5',
    text: `In this episode, Keith and Jesse discuss how prioritizing fun can rekindle passion, create connection, and keep your partnership exciting. Learn how to create a container for fun, avoid becoming a Debbie Downer, and rediscover the joy in your relationship. Find out why fun is the foundation of a lasting connection and why it's essential to maintain it throughout your journey together. Listen in! ____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Married Game Podcast: Fun Is The Fountainhead',
  },
  {
    id: 'podcast:mg:6c693b28-697d-4691-b540-4c2e55cc3d76',
    text: `In this episode, Keith is joined by Ryan Stewman, and they discuss the secrets of maintaining a successful marriage. Discover how the G-Code principles can be applied not only to business but also to relationships, trust, and commitment. Learn from Ryan's personal experiences, his journey through multiple marriages, and the profound lessons he's gained in building a thriving partnership. Listen in! ____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Married Game Podcast: The G-Code Of Marriage With Ryan Stewman',
  },
  {
    id: 'podcast:mg:efbbce57-83ef-4654-98b2-6886befae457:0',
    text: `In this episode, Keith and Jesse dive deep into the importance of serving and being present in your relationship. They share personal experiences and insights on how radical presence and acts of service can transform your connection, making it stronger and more fulfilling. Learn how to get out of your head and into your body for a more passionate and connected partnership. Plus, discover what Keith and Jesse find most attractive about each other that goes beyond physical appearances. Listen in!`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Married Game Podcast: Balancing Masculine And Feminine Energies',
  },
  {
    id: 'podcast:mg:efbbce57-83ef-4654-98b2-6886befae457:1',
    text: `____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    topic: 'Married Game Podcast: Balancing Masculine And Feminine Energies',
  },
  {
    id: 'podcast:mg:855fe685-3450-4138-801e-8548ef1589ee',
    text: `In this episode, Keith is joined by Brian Gapik, and they discuss personal growth and transformation. Brian shares his candid experiences from feeling stuck and floundering in life to embracing the power of self-awareness and coaching. Discover how Brian's willingness to be coachable and open to change led to a remarkable transformation in his marriage, business, and overall life. Listen in! ____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Married Game Podcast: From Floundering To Thriving With Brian Gapik',
  },
  {
    id: 'podcast:mg:00bd71a6-5cad-4a41-a65b-f2216f171915',
    text: `In this episode, Keith and Jess are both joined by Steven and Marianne Kalas, and they discuss the Enneagram personality types, how different energies shape your relationship, embracing the radical "we," how to deal with grievances, and how understanding different personality types can lead to deeper connections and a transformative journey in love. Listen in! ____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    topic: 'Married Game Podcast: The Married Game Wizard With Steven And Marianne Kalas',
  },
  {
    id: 'podcast:mg:aa6e7819-21d1-4647-b67b-7794acacfeab:0',
    text: `In this episode, Keith dives deep into the concept of settling in relationships. He introduces two types of settling that can ruin a man's situation: one where he lets himself decline in various aspects of life and the other where he remains in an unfulfilling relationship. Keith emphasizes the need for men to continually strive for greatness in every area and stand up for their desires, regardless of societal norms. He also challenges you to break free from fear, redefine your standards, and be the example that you expect from your partner. Listen in!`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Married Game Podcast: Rise Above Settling',
  },
  {
    id: 'podcast:mg:aa6e7819-21d1-4647-b67b-7794acacfeab:1',
    text: `____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    topic: 'Married Game Podcast: Rise Above Settling',
  },
  {
    id: 'podcast:mg:91933e0b-6bab-48a0-8ae2-29ac523f5e4f',
    text: `In this episode, Keith is joined by Adam Lyons, and they talk about the intricate layers of human needs within relationships. From unlocking physiological necessities and safety to the delicate dance of love and belonging, they discuss how these needs intertwine with success and self-actualization. They also explore how recognizing and embracing desires can lead to personal growth and transcendence, ultimately creating a harmonious bond. Listen in! ____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    topic: 'Married Game Podcast: Relationship Hierarchy With Adam Lyons',
  },
  {
    id: 'podcast:mg:45a6ca34-799b-4b14-b49c-00aa671cfe28',
    text: `In this episode, Keith is joined by Joel Staley, and they dive into the world of true male fitness, revealing the secrets behind sustainable weight loss, peak energy, and irresistible confidence. From Joel's personal journey, where Rocky marathons ignited his passion, to the revelation of intermittent fasting's potential, they challenge conventional fitness norms and encourage you to elevate your physicality, family life, and inner strength. Listen in! ____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    dial: 'PLAYER',
    topic: 'Married Game Podcast: True Masculine Fitness With Joel Staley',
  },
  {
    id: 'podcast:mg:5483141c-89cd-41c8-b28c-8cebcc2755e4',
    text: `In this episode, Keith and Jesse dive deep into the power dynamics of relationships. They discuss how becoming your best self, both physically and emotionally, can create a profound impact in your relationship. Learn how to empower yourself to ask for what you want confidently and authentically, ultimately leading to a stronger and more fulfilling connection. Listen in! ____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    dial: 'POWER',
    topic: 'Married Game Podcast: Leveling Up To The Best Version Of Yourself',
  },
  {
    id: 'podcast:mg:591d0129-0348-48de-a0cc-bbcbf64b4d0e',
    text: `In this episode, Keith and Jesse discuss their journey of overcoming jealousy and building a strong foundation of trust in their relationship. They share insights on finding security within oneself, serving others, and focusing on personal growth, ultimately creating a powerful bond that allows them to impact lives positively. Listen in! ____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    dial: 'POWER',
    topic: 'Married Game Podcast: Make The Choice Not To Be Jealous',
  },
  {
    id: 'podcast:mg:85a360b0-12f6-49aa-91ad-75de3c2aa178',
    text: `In this episode, Keith shares his powerful story of transformation and accountability. Discover the truth about personal growth, the importance of brotherhood, and how taking responsibility can lead to a fulfilling life and a thriving relationship. Listen in! ____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    dial: 'POWER',
    topic: 'Married Game Podcast: Unleashing Accountability And Empowerment',
  },
  {
    id: 'podcast:mg:f65b01ca-b5fd-49f1-a8f8-97ac4457deb5',
    text: `In this episode, Keith and Jesse discuss the power of vulnerability and open communication in relationships. They uncover the transformative impact of reframing negative patterns, asking for what you need, and embracing your partner as a teammate on the journey of love and growth. They also provide actionable tips to create an empowered and connected relationship. Listen in! ____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Married Game Podcast: Reframing Relationships',
  },
  {
    id: 'podcast:mg:7dcd6c5e-8742-46dd-8aba-94ed203b48cb',
    text: `In this episode, Keith and Jesse discuss the challenges of personal growth within a relationship, discussing the struggles of finding a new identity, changing expectations, and learning to communicate effectively amidst the messy process with practical tips for fostering understanding and creating a safe space for growth. Listen in! ____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    topic: 'Married Game Podcast: The Messy Journey Of Relationship Growth',
  },
  {
    id: 'podcast:mg:223fadd4-eee3-4eb4-af86-2f550afd59ab',
    text: `In this episode, Keith and Jesse discuss the transformative power of their coaching program and the impact it has on relationships. They talk about the importance of vulnerability, truth-sharing, and the value of seeking external perspectives. Join them as they tackle common relationship challenges and offer practical advice for couples to achieve greater fulfillment. Listen in! ____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    dial: 'POWER',
    topic: 'Married Game Podcast: Unlocking Transformation And Relationship Fulfillment',
  },
  {
    id: 'podcast:mg:c64d053a-9cea-4156-ad00-9ea50b01c0e2',
    text: `In this episode, Keith and Jesse discuss the importance of effective communication in relationships and sharing strategies for couples to navigate intimacy and desire. They share practical tips and a unique vocabulary for couples to communicate their needs, ensuring that rejection turns into rainchecks and intimacy flourishes. Listen in! ____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Married Game Podcast: From Never To Raincheck',
  },
  {
    id: 'podcast:mg:fbc13bdd-57fc-4185-9bbe-1edfca3f6058',
    text: `In this episode, Keith addresses all of you women listeners and shares his version of the truth about what men truly desire in a marriage. He emphasizes the importance of women supporting their husbands and challenges them to set a higher standard for themselves. Keith offers provocative insights into how women can transform their marriages by becoming the best wives and partners they can be, ultimately leading to greater fulfillment and satisfaction for both spouses. Listen in! ____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Married Game Podcast: What Your Husband Really Wants',
  },
  {
    id: 'podcast:mg:ad096444-143d-495b-9374-5e59b416fead',
    text: `In this episode, Keith discusses the importance of compliments in relationships, especially for women. He discusses the different types of compliments and how they impact men, emphasizing the need for proactive compliments that highlight character traits. Keith also explores the connection between resentment and complimenting and encourages you to shift your focus to positivity, ultimately improving your relationships and your own life. Listen in! ____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    dial: 'POWER',
    topic: 'Married Game Podcast: The Power Of Compliments',
  },
  {
    id: 'podcast:mg:e5c2965d-8458-4595-9cad-ced35b02ee1b:0',
    text: `In this episode, Keith is joined by Taylor Welch, and they discuss the struggle of walking away from something, the ongoing wrestling with decisions, and the importance of building better systems rather than viewing failures as personal shortcomings. They explore the power of perspective, learning from the past, vulnerability in relationships, the pursuit of personal growth, and the necessity of perseverance in the face of adversity.`,
    sourceType: 'PODCAST',
    dial: 'POWER',
    topic: 'Married Game Podcast: Mirror Neurons And Thriving Marriages With Taylor Welch',
  },
  {
    id: 'podcast:mg:e5c2965d-8458-4595-9cad-ced35b02ee1b:1',
    text: `They also talk about the fascinating connections between attitude, mirror neurons, and personal well-being, how our attitudes shape our experiences and the profound impact of mirroring others' emotions. Listen in! ____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    topic: 'Married Game Podcast: Mirror Neurons And Thriving Marriages With Taylor Welch',
  },
  {
    id: 'podcast:mg:72b280c4-03fb-4c32-9f38-b07e7cb3b72c',
    text: `In this episode, Keith is joined by Hans Molenkamp, and they discuss turning ideas into successful ventures, creating Triumph United as a marketing agency for athletes to build a thriving brand, how to approach competition and handling doubts, sponsoring top fighters, as well as building trust and relationships in the industry. Listen in! ____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    topic: 'Married Game Podcast: The Journey To Mainstream Success With Hans Molenkamp',
  },
  {
    id: 'podcast:mg:910ad14f-6651-46e0-a094-9c4511ddd079:0',
    text: `In this episode, Keith discusses his insights on what every man wants in his relationship, and how to achieve it by leading and serving through the masculine. He shares a powerful testimonial of a man who followed their process and transformed his relationship from asexual to sexually expressed, and how you can achieve the same. Keith also talks about the importance of waking up to reality and standing in your power, leading yourself, and becoming a better version of yourself. Listen in!`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Married Game Podcast: Wake Up And Stand In Your Power',
  },
  {
    id: 'podcast:mg:910ad14f-6651-46e0-a094-9c4511ddd079:1',
    text: `____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    topic: 'Married Game Podcast: Wake Up And Stand In Your Power',
  },
  {
    id: 'podcast:mg:dd163784-46d5-4b58-932e-d80c1602073b',
    text: `In this episode, Keith and Jesse discuss and debunk different myths about relationships and marriage and doing things out of the norm to make yourself better and happier. Listen in! ____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Married Game Podcast: Debunking Myths',
  },
  {
    id: 'podcast:mg:03df564c-414d-4d9b-94e6-e5d44f7e9ff8:0',
    text: `In this episode, Keith and Jesse discuss empowering yourself to get what what you want from your wife and becoming empowered before you start acting empowered, pressuring your wife to have sex with you and her excuses to avoid having sex, cleaning up your side of the street before trying to fix the relationship, taking the guesswork out of the relationship by listening to your wife's needs and wants and then clearly stating your own needs and wants, letting go of resentment, and the "five to thrive." Listen in!`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Married Game Podcast: Pressure Is Not A Bad Thing',
  },
  {
    id: 'podcast:mg:03df564c-414d-4d9b-94e6-e5d44f7e9ff8:1',
    text: `____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    topic: 'Married Game Podcast: Pressure Is Not A Bad Thing',
  },
  {
    id: 'podcast:mg:4797c260-b164-4b8b-8c00-9b96628ad355',
    text: `In this episode, Keith is joined by Bryce Kimble, and they discuss his unique journey with the Married Game program, how to become a provocateur, the importance of having a good coach, building trust with women, being a better provider, the notion of entitlement in relationships, the human desire for progress and growth, and pushing yourself to become a new level of man. Listen in! ____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    dial: 'PRODUCER',
    topic: 'Married Game Podcast: Progress Together With Bryce Kimble',
  },
  {
    id: 'podcast:mg:2289171f-9b7c-49b1-807c-b9cfba73ada1',
    text: `In this episode, Keith and Jesse discuss pushing each other's buttons in a marriage, finding humor to diffuse potentially contentious situations, getting curious about your emotions, and becoming your wife's best option every single day. Listen in! ____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Married Game Podcast: Finding All The Green Combs',
  },
  {
    id: 'podcast:mg:713e5e94-5d67-48c0-85d4-db9f261b346f',
    text: `In this episode, Keith and Jesse discuss how baffling and bothersome it is for you men that are suffering with a cancer in your soul to have to "check with" your wife, who is actually begging you to step up, before becoming the best version of yourself. Listen in! ____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Married Game Podcast: Have Some Goddamn Respect For Yourself',
  },
  {
    id: 'podcast:mg:d2a757fd-fba0-4fd0-bd16-2054607395f7',
    text: `In this episode, Keith and Jesse discuss the inverse relationship between communication and passion, the power of missing each other and creating mystery, and the progression in a relationship from lust, to love, to building a life together. Listen in! ____________________________ For more information or to speak with Keith directly, please visit marriedgame.com`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Married Game Podcast: Lust, Love, And Life',
  },
  {
    id: 'podcast:pm:e00026f0-1f31-4635-80c6-3ff20a63c0a4',
    text: `Real growth takes more than just a few days. In this episode Keith discusses how hard it is to keep doing the necessary daily tasks to see progress. He tells us that we need to have faith, trust, hope and a process to get past not seeing immediate results. He will show you how to overcome the habit of doing just enough to get by. Listen in! __________________ To learn more about raising Private Money, go to www.PrivateMoneyPro.com`,
    sourceType: 'PODCAST',
    dial: 'PRODUCER',
    topic: 'Private Money Secrets: 103: Is Faith Real?',
  },
  {
    id: 'podcast:pm:5ec520d9-147e-4bcd-ac4d-e653fcde894c',
    text: `What is your standard? Every. Single. Thing. in your life is a result of the standards and habits you have toward either winning or losing. This relates to every result, every relationship, every dollar... What is your standard? Let's discuss. __________________ To learn more about raising Private Money, go to www.PrivateMoneyPro.com`,
    sourceType: 'PODCAST',
    dial: 'PRODUCER',
    topic: 'Private Money Secrets: 094: Winning Isn\'t For Everyone',
  },
  {
    id: 'podcast:pm:33c5fce4-cfe8-4063-8c64-b0e109316b3b',
    text: `We don't have problems in our business. We have personal problems that show up in our business. ...and that's why we're discussing personal growth. In this episode, Keith discusses the value of resistance in your business and how it's actually forcing your to level up. Let's discuss. __________________ To learn more about raising Private Money, go to www.PrivateMoneyPro.com`,
    sourceType: 'PODCAST',
    dial: 'PRODUCER',
    topic: 'Private Money Secrets: 090: Resistance Makes Your Grow',
  },
  {
    id: 'podcast:pm:d1e1a6e9-9c8d-4870-81bd-ea4b5f630c0b',
    text: `Why do you win? And why do 9 out of 10 businesses fail? This simple, shift in your mindset makes you win EVERY SINGLE TIME. Let's dive in. __________________ To learn more about raising Private Money, go to www.PrivateMoneyPro.com`,
    sourceType: 'PODCAST',
    dial: 'PRODUCER',
    topic: 'Private Money Secrets: 086: Why 9 Out of 10 Businesses Fail',
  },
  {
    id: 'podcast:pm:2552201b-185f-42f6-97bc-b38eab47a38d',
    text: `When you take action toward a specific result, the growth happens immediately! But you can't see it yet. So, change your perspective on how long it takes. This episode is powerful! Listen in. __________________ To learn more about raising Private Money, go to www.PrivateMoneyPro.com`,
    sourceType: 'PODCAST',
    dial: 'PRODUCER',
    topic: 'Private Money Secrets: 072: Take the Long Way',
  },
  {
    id: 'podcast:pm:973ed10c-4a50-4a33-b3b7-b88f580a51d4',
    text: `In today's episodes, Keith shares a bit about his new program co-founded with Brad Lea called "Relationships That Pay." Good relationships take time. And in the Private Money game, you'll have to meet and cultivate relationships with people that you desire benefit from without coming across needy or downright opportunistic. So, how do you do it best? Let's dive in. _______ To learn more about raising Private Money, go to www.PrivateMoneyPro.com`,
    sourceType: 'PODCAST',
    dial: 'PRODUCER',
    topic: 'Private Money Secrets: 045: Good Relationships Take Time',
  },
  {
    id: 'podcast:pm:c38a1ef1-8d08-4d7f-9f88-94fcb892bd9c',
    text: `Venturing into the Private Money space is scary. It's high stakes but also a great potential. Fear is natural. In today's episode, Keith shares what your fear means and gives you insight into how to use is it for your betterment. Get more deals, make more money, expand your network by harnessing your fear for what it is. GROWTH. _______ To learn more about raising Private Money, go to www.PrivateMoneyPro.com`,
    sourceType: 'PODCAST',
    dial: 'PRODUCER',
    topic: 'Private Money Secrets: 044: Fear Equals Growth',
  },
  {
    id: 'podcast:pm:386c1fca-e94f-4b59-b485-c41c1aa1f937',
    text: `Merry Christmas! And let's talk about skills. Today on this wonderful day let this message resonate with you. This episode is an invitation for you to finally succeed. What say ye? RelationshipsThatPay.com _______ To learn more about raising Private Money, go to www.PrivateMoneyPro.com`,
    sourceType: 'PODCAST',
    dial: 'PRODUCER',
    topic: 'Private Money Secrets: 031: The One Skill You Need',
  },
  {
    id: 'podcast:pm:9584474e-614b-4873-880b-675d4410604e',
    text: `In this episode, Keith destroys one of the silliest "truths" that 99% of the people believe... ...that holds them back. So, let's discuss how to actually build relationships that pay. _______ To learn more about raising Private Money, go to www.PrivateMoneyPro.com`,
    sourceType: 'PODCAST',
    dial: 'PRODUCER',
    topic: 'Private Money Secrets: 028: How to Build Relationships That Pay',
  },
  {
    id: 'podcast:pm:68ef0cf7-e328-445c-a959-8164b8699819',
    text: `Raising Private Money is a scary thing. It's one of the reasons why we focus on mindset and perspectives on Private Money Secrets. But what does your FEAR really mean for you? It's biggest and more of a blessing than may be considering. Listen in! _______ To learn more about raising Private Money, go to www.PrivateMoneyPro.com`,
    sourceType: 'PODCAST',
    dial: 'PRODUCER',
    topic: 'Private Money Secrets: 025: Your Fear Is Your Marker',
  },
  {
    id: 'podcast:pm:f68e3c3f-7b4b-410d-baad-0f6d1880974c',
    text: `Using an example from a short drive with my wife, I remind you how being a "sheep" will get you right there with the herd. Are you a follower? Or a leader? Do you want to be fed just a little? Or feast? Let's dive in. _______ To learn more about raising Private Money, go to www.PrivateMoneyPro.com`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Private Money Secrets: 018: Stop Being a Sheep',
  },
  {
    id: 'guest:eofire:four-dials',
    text: `From Entrepreneurs on Fire: Keith Yackey experienced his wife leaving him due to lost attraction. He became determined to understand this dynamic. Core belief: Success doesn't require being contrarian. Boring produces boring results; fun creates fun experiences. Personal accountability comes first — "Until you can say that you are the most attractive version of yourself, you do not have the right to be pointing the finger at her." The primary reason women stop initiating sexual contact: loss of attraction to their partner.`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Guest: Entrepreneurs on Fire - Getting Your Wife To Want You Again',
  },
  {
    id: 'guest:eofire:parenting-dial',
    text: `From Entrepreneurs on Fire - The Parenting Dial: Focus on demonstrating active parenting presence. Show partnership in child-rearing responsibilities. Research indicates that effective fatherhood creates attraction for many women. Being an engaged, present father is one of the most attractive things a man can do.`,
    sourceType: 'PODCAST',
    dial: 'PARENT',
    topic: 'Guest: EOFire - The Parenting Dial',
  },
  {
    id: 'guest:eofire:partner-producer',
    text: `From Entrepreneurs on Fire - The Partner and Producer Dials: The Partner Dial focuses on creating unity and shared purpose, demonstrating genuine partnership, actively supporting your partner's priorities and goals. The Producer Dial focuses on ambition and purpose-driven living, maintaining drive for growth and improvement, cultivating a mission extending beyond personal interests, demonstrating daily motivation.`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Guest: EOFire - Partner & Producer Dials',
  },
  {
    id: 'guest:eofire:player-dial',
    text: `From Entrepreneurs on Fire - The Player Dial: Focus on maintaining romantic excitement. Replicate the effort from early courtship. Create memorable experiences together. Remind your partner of her identity beyond parenting. Embrace spontaneity and fun. Keith references that "Boring equals boring; fun equals fun." Partners who generate excitement together experience deeper intimacy and more satisfying physical relationships.`,
    sourceType: 'PODCAST',
    dial: 'PLAYER',
    topic: 'Guest: EOFire - The Player Dial',
  },
  {
    id: 'guest:orderofman:5dials',
    text: `From Order of Man with Ryan Michler: Keith discusses the ROI (Return of Intimacy) in marriage, how a man gains his power back after giving it away, the "mommy matrix," why seeking her validation will backfire, and the 5 dials of a powerhouse marriage. "When guys say 'I do' they act as though it's done." The five dials help men measure effectiveness: Women want you to be a good parent, to be her partner, to be a producer, to have fun, and to do what you say you're going to do when you say you're going to do it. Become the guy that any woman would be thrilled to be with.`,
    sourceType: 'PODCAST',
    dial: 'POWER',
    topic: 'Guest: Order of Man - 5 Dials to a Powerful Marriage',
  },
  {
    id: 'guest:dadedge:married-game',
    text: `From The Dad Edge with Larry Hagner: Keith Yackey discusses authentic communication in marriage, building attraction techniques in relationships, emotional intelligence in romantic partnerships, leadership skills applied to marriage, enhancing marital fun and connection, relationship dynamics and transformation, overcoming divorce through practical strategies, personal development for couples, reinventing marital connections, provocative approaches to relationship improvement, nurturing partnership growth, and empowering couples guidance.`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Guest: The Dad Edge - The Married Game',
  },
  {
    id: 'guest:dadwork:5dials-dads',
    text: `From Dad.Work with Curt Storring: Keith discusses how to have more sex with your wife and why it's so much more important than just getting your physical desires met. Why extreme ownership and taking full responsibility for yourself in your marriage is the key to success. Trust and integrity as the baseline for intimacy. Keith's 5 dials that lead to an unreasonably good marriage. When his wife left him 5 years ago, he realized that he was the problem and that his wife was no longer attracted to him. Since getting her back, Keith has dedicated his life to teaching men how to become the most attractive version of themselves.`,
    sourceType: 'PODCAST',
    dial: 'POWER',
    topic: 'Guest: Dad.Work - 5 Dials for Extraordinary Intimacy',
  },
  {
    id: 'guest:loriharder:attract',
    text: `From Earn Your Happy with Lori Harder: Keith Yackey shares his journey of helping men restore attraction in their marriages so wives want to initiate intimacy again. He presents a proven five-dial process. Working on yourself first to show up as your best version for your partner. Keith's wife's wake-up call five years ago. Stepping into fatherhood responsibilities. Finding power balance in marriages. Role of compromise in relationships. Self-discipline and the 75 Hard challenge as tools for personal transformation.`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Guest: Lori Harder - Attract What You Want',
  },
  {
    id: 'guest:mantalks:attraction',
    text: `From ManTalks with Connor Beaton: Keith Yackey discusses the recipe for attraction in long-term relationships. Strategies for building and preserving intimacy, sexual connection, vibrancy, and excitement in marriages. Personal experiences from his own marriage alongside practical frameworks for sustaining emotional and physical bonds between partners. The key is maintaining passion through intentional effort, not waiting for it to happen spontaneously.`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Guest: ManTalks - Recipe for Attraction in Long-Term Relationships',
  },
  {
    id: 'guest:thinkunbroken:word',
    text: `From Think Unbroken with Michael Unbroken: Keith discusses how to keep your word to yourself. "You're not what you say you say, you're what you do." Building character and accountability. The importance of being clear about direction. Holding yourself accountable. Being a person of character who does what they say they're going to do. Over eighty percent of divorces don't have to happen if both partners commit to growth.`,
    sourceType: 'PODCAST',
    dial: 'POWER',
    topic: 'Guest: Think Unbroken - Keep Your Word to Yourself',
  },
  {
    id: 'guest:chrisharder:save',
    text: `From The Chris Harder Show: Keith transitioned from being a pastor to flipping 200 properties in two years. His mother's passing at age 28 significantly impacted his life approach. Keith's wife left him as he focused excessively on business success. He eventually recognized that "95% of the failure of his marriage was his fault." Core message: "You have to become the most attractive version of you. And the most attractive version of you loves themselves." Integrity, discipline, and self-respect are essential for relationship recovery. Loving oneself is foundational to loving others effectively.`,
    sourceType: 'PODCAST',
    dial: 'POWER',
    topic: 'Guest: Chris Harder - How to Save Your Relationship',
  },
  {
    id: 'guest:danclark:bestversion',
    text: `From Dan Clark: Keith emphasizes that becoming your best self requires three elements: curiosity, discipline, and personal integrity. "Keeping my word to myself is the only thing that makes me feel like I'm an empowered human being." Keith credits the 75 Hard program with teaching him that self-trust develops through consistent follow-through on commitments, regardless of scale. True success requires balance across physical, mental, spiritual, and relational dimensions. External achievements mean little without personal integrity and healthy relationships. Change begins with decisive commitment: "Everything starts with a decision."`,
    sourceType: 'PODCAST',
    dial: 'POWER',
    topic: 'Guest: Dan Clark - Becoming the Best Version of Himself',
  },
  {
    id: 'guest:caryjack:5dials',
    text: `From The Happy Hustle with Cary Jack: "Attraction in relationships isn't just about chemistry — it's a skill you can develop." Keith shares how his wife left him, and how he transformed that experience into the Five Dials framework. Common mistakes that kill attraction: passive aggressiveness and pouting, lack of personal growth and self-improvement, abandoning playfulness and flirtation. Business principles — growth, consistency, value creation — directly apply to relationships. Optimizing business success while neglecting relationships creates dangerous imbalance.`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Guest: Cary Jack - 5 Dials to Becoming a Better Partner',
  },
  {
    id: 'guest:worldneedsmen:3lies',
    text: `From The World Needs Men with Franklin Swann: Keith discusses the Three Lies that destroy marriages. Lie 1: "I Married the Wrong Woman" — this is almost never true. Lie 2: "Women Aren't Into Sex" — false; they're not into sex with a man who doesn't turn them on. Lie 3: "Men Are Perverts for Wanting Sex" — wanting physical intimacy is normal and healthy. The Five Dials for this episode: Being a good parent, being a best friend, producing, being fun and playful, and staying in your power.`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Guest: World Needs Men - Three Lies Men Believe',
  },
  {
    id: 'guest:bradlea:wifeback',
    text: `From Dropping Bombs with Brad Lea: Keith Yackey reveals how to get your wife to fall in love with you again. The key is not chasing her — it's becoming the man she fell in love with, and then some. When Keith's wife left, he didn't beg or plead. He worked on himself. He got in shape, got disciplined, rebuilt his integrity, became the most attractive version of himself. And she came back. The lesson: you can't negotiate attraction. You can only become more attractive through genuine self-improvement.`,
    sourceType: 'PODCAST',
    dial: 'POWER',
    topic: 'Guest: Brad Lea - How to Get Your Wife to Fall in Love Again',
  },
  {
    id: 'guest:travischappell:monogamy',
    text: `From Travis Makes Friends with Travis Chappell: Keith Yackey and Jesse Marquez discuss "monogamy plus" — the idea that a committed marriage can be exciting, passionate, and deeply fulfilling if both partners invest intentionally. They discuss how to get your ex back, the dynamics of modern marriage, and why most men give up too easily on their relationships. The "plus" in monogamy means adding adventure, growth, challenge, and playfulness to a committed relationship.`,
    sourceType: 'PODCAST',
    dial: 'PARTNER',
    topic: 'Guest: Travis Chappell - Monogamy Plus',
  },
  {
    id: 'guest:solopreneur:fears',
    text: `From The Solopreneur Hour: Keith Yackey on conquering huge fears in life and business. Keith organized a 500-person live event in Las Vegas without prior event-running experience. The central theme: finding coaches and mentors to accelerate progress across various pursuits. Success requires being willing to look foolish, fail publicly, and keep going. Keith's mother's death at age 56 drove him to adopt a "No Regrets" philosophy and launch the real estate business he'd previously feared starting.`,
    sourceType: 'PODCAST',
    dial: 'POWER',
    topic: 'Guest: Solopreneur Hour - Conquering Huge Fears',
  },
];
